= Docker environment for the data science training

== Launch the env 

=== On all environment

First you need to download the latest version of those plugins, and put them inside the `plugins` directory  : 

* APOC : https://github.com/neo4j-contrib/neo4j-apoc-procedures/releases/
* Graph Algos : https://github.com/neo4j-contrib/neo4j-graph-algorithms/releases/
  
For example, the current when I write this file are : 

* https://github.com/neo4j-contrib/neo4j-graph-algorithms/releases/download/3.5.3.1/graph-algorithms-algo-3.5.3.1.jar
* https://github.com/neo4j-contrib/neo4j-apoc-procedures/releases/download/3.5.0.2/apoc-3.5.0.2-all.jar 
  

Then you just have to run `docker-compose up`

=== On linux

On linux you can directly run the script `run.sh`, it will download everything you need and also run the `docker-compose up` command for you.

== Next steps 

=== Neo4j : change the password

Go to http://localhost:7474/browser, put the default login/password (ie. neo4j /neo4j ), and you will be asked for the new admin.

=== Jupyter

Search the Jupyter `token` inside the logs of docker. You should see something similar to that : `[I 17:39:57.299 NotebookApp] http://(9d6f11a3c1a1 or 127.0.0.1):8888/?token=04833158d59cd1ac094602f9b097822a904fa285607e1c59`

Then go to http://localhost:8888/ and copy to the token

IMPORTANT: The Neo4j URL for the notebook is `bolt://data-science-training-neo4j`
